### ISSUE TITLE
How to use LITNet as a beckbone of object detection

### ISSUE THREAD

**Issue by sunhuisunhui** [zhuang-group/LIT#1]
Could you please release the code of using LITNet as a beckbone of RetinaNet as mentioned in your paper? I wonder how to use it as a beckbone for object detection...

**Comment by HubHop** [comment]
Hi @sunhuisunhui,

Thank you for your question. We will release the code for object detection and semantic segmentation this weekend.

Best,
Zizheng

**Comment by HubHop** [comment]
Hi @sunhuisunhui,

We have released the code for object detection and semantic segmentation, along with the checkpoints and training logs. Please do not hesitate to ask me if you have any further questions.

Best,
Zizheng
