### ISSUE TITLE
Problem about DCN

### ISSUE THREAD

**Issue by jarygrace** [zhuang-group/LIT#2]
I have some problems about compiling DCN, thus it is hard for me to use the DCN.deform_conv2d_forward and DCN.deform_conv2d_backward functions. 
Can 'deform_conv2d_naive' be used instead of this part? Or is there other methods for me to accomplish this DCN.deform_conv2d part?

**Comment by HubHop** [comment]
Hi @jarygrace, 

Thanks for using LIT. Could you please specify what errors you have when compiling DCN? We do not test deform_conv2d_naive as it can be much slower than the CUDA implementation.

**Comment by wangru1026** [comment]
I also encountered the same problem, but I did not understand how to work properly. Can you be more specific?

**Comment by wangru1026** [comment]
> I have some problems about compiling DCN, thus it is hard for me to use the DCN.deform_conv2d_forward and DCN.deform_conv2d_backward functions. Can 'deform_conv2d_naive' be used instead of this part? Or is there other methods for me to accomplish this DCN.deform_conv2d part?
