### ISSUE TITLE
Problem about DCN and DCNv2

### ISSUE THREAD

**Issue by zexulin1** [zhuang-group/LIT#3]
DCN and DCNv2 are the same packages? I installed DCNv2 but not found the forward and backward function.

**Comment by HubHop** [comment]
Hi @whitebear-coder, Thanks for your interest!

`mm_modules` contains implementation for both DCN and DCNv2. You can use DCN by
```python
from mm_modules.DCN.modules.deform_conv2d import DeformConv2dPack
```
For DCNv2, please refer to `ModulatedDeformConv2dPack`. For example,
```python
from mm_modules.DCN.modules.modulated_deform_conv2d import ModulatedDeformConv2dPack
```
