### ISSUE TITLE
ModuleNotFoundError: No module named 'DCN'

### ISSUE THREAD

**Issue by wo0423** [zhuang-group/LIT#5]
firstly, thanks for your work! When I debug the code for the segmentation part, I encountered the problem:
![image](https://user-images.githubusercontent.com/59550614/217842141-dcf4c46f-bc61-478c-85f2-d68d7d735d17.png)
which is used to introduce deform_conv2d_forward and deform_conv2d_backward, but I find them in  a file with the suffix h， and it can not be called directly， I want to know if there is any way to solve this problem， looking forward to your reply,

**Comment by HubHop** [comment]
Hi @wo0423, thanks for your interest! It seems that you didn't install DCN in your python env. Please try the following:

```bash
conda activate [your_python_env]
cd mm_modules/DCN
python setup.py build install
```

**Comment by wo0423** [comment]
I got it, thank you very much

**Comment by wo0423** [comment]
Sorry to bother you again, but I didn't find the default settings in the relevant config file when I ran it, but I added default=..., It's still wrong. I can't understand this part very well. Can you give me some help? Thank you
![image](https://user-images.githubusercontent.com/59550614/218033152-6293c093-f949-4ec9-8d80-0dc085317cdb.png)

**Comment by HubHop** [comment]
Hi @wo0423, please note that `train.py` requires a configuration file for training your model. In order to train a model on GPUs, you can run:

```bash
bash tools/dist_train.sh <CONFIG_FILE> <GPU_NUM> --options model.pretrained=<PRETRAIN_MODEL> [model.backbone.use_checkpoint=True] [other optional arguments] 
```
For example, you can run the following command on a single GPU.
```bash
bash tools/dist_train.sh configs/lit/lit_ti_fpn_r50_512x512_80k_ade20k.py 1 --options model.pretrained=./pretrained/lit_ti.pth
```
More details can be found at https://github.com/ziplab/LIT/tree/main/segmentation#training.

**Comment by wo0423** [comment]
Thank you very much for your reply! In fact, my puzzle is how to set the config file if I run train.py through pycharm instead of using commands

**Comment by HubHop** [comment]
To debug this project in PyCharm. You can do the following:
1. Open LIT/segmentation in PyCharm

2. Set you debug configuration like this:

![Screenshot from 2023-02-10 21-26-43](https://user-images.githubusercontent.com/20661773/218068605-f0931eb2-22cc-4d5a-88c9-2357d9354cd3.png)

3. In the window of 'parameters':
```
--nproc_per_node=1
--master_port=1234
tools/train.py
configs/lit/lit_ti_fpn_r50_512x512_80k_ade20k.py
--launcher
pytorch
``` 
3. In the window of 'Working Directory', remember to exclude 'tools'
4. Remember to put your pretrained weights under ./pretrained/

Now it should work.

**Comment by wo0423** [comment]
I set this as above, and I get the error:
![image](https://user-images.githubusercontent.com/59550614/218074551-6b6cfc40-c7bb-47ea-8e94-f50c7fc4b0de.png)
I only have one GPU

**Comment by wo0423** [comment]
Thank you for your patience. I solved it.
